host_list:
  1:
  - nt
  - localhost
  - null
  - null
  2:
  - posix
  - 192.168.15.47
  - oracle
  - oracle123
  3:
  - posix
  - 192.168.15.47
  - oracle
  - oracle123
host_map:
- host: 2
  shards: 0:20
- host: 3
  shards: '20:40'
