BINDSIZE: '200003'
COLUMNARRAYROWS: '10000'
DIRECT: 'TRUE'
ERRORS: '10'
MULTITHREADING: 'TRUE'
PARALLEL: 'TRUE'
READSIZE: '200000'
SKIP_INDEX_MAINTENANCE: 'TRUE'
SKIP_UNUSABLE_INDEXES: 'TRUE'
STREAMSIZE: '500000'
